### ISSUE TITLE
Random comma at top of list of students

### ISSUE THREAD

**Issue by jesshmusic** [mzenzie/320MusicLessonPlanner#20]
Not sure where it's coming from, investigation ongoing.

**Comment by nsimsiri** [comment]
There was a comma here at the end of line 14
![screen shot 2015-03-16 at 2 04 48 am](https://cloud.githubusercontent.com/assets/3226241/6661320/e11cf19c-cb80-11e4-81c5-c7f713cc58f6.png)
.  I fixed it in the ServerBranch.
