### ISSUE TITLE
Deleting from SRecord also Deletes in other tables <Delete Cascade>

### ISSUE THREAD

**Issue by nsimsiri** [mzenzie/320MusicLessonPlanner#24]
current Query doesn't work: 

DELETE SRecord, Schedule FROM SRecord INNER JOIN Schedule ON SRecord.sid=Schedule.sid WHERE SRecord.sid = 1

**Comment by jesshmusic** [comment]
@nsimsiri Is this still a bug?

**Comment by jesshmusic** [comment]
I' assuming this has been resolved....
