### ISSUE TITLE
Edit Student Record needs implemented.

### ISSUE THREAD

**Issue by jesshmusic** [mzenzie/320MusicLessonPlanner#32]
Shouldn't be too difficult.

**Comment by xiuxiuzhu** [comment]
I will solve the issue since it relates to database

**Comment by nsimsiri** [comment]
Finished by have to FIX
- NEED TO RECODE PRIMARY KEY FROM EMAIL, INSTRUMENT to SID -

**Comment by xiuxiuzhu** [comment]
It is implemented
