### ISSUE TITLE
[important for UI to know] List StudentRecord doesn't retrieve respective Schedules

### ISSUE THREAD

**Issue by nsimsiri** [mzenzie/320MusicLessonPlanner#46]
If Client Calls query to get all student records at once (GET /api/studentRecord/) - each of them will have an empty lessonSchedules field. However, if the client gets a specific student record (GET /api/studentRecord/?id=<specific id>) then this one student record's schedule can be accessed through studentRecord.lessonSchedules. 

Sqlite3 doesn't support looping with queries.

**Comment by jesshmusic** [comment]
Fixed.
We have a decent workaround for this.
Going to open a new issue for the separate problem of Today View not updating.
