### ISSUE TITLE
Frontpage logo is semi covered on 1366x768 resolution

### ISSUE THREAD

**Issue by mzenzie** [mzenzie/320MusicLessonPlanner#53]
![image](https://cloud.githubusercontent.com/assets/1862891/6947113/05c42962-d873-11e4-96d5-47b5dfa4fe50.png)

This could be fixed by making the bar transparent.

**Comment by mzenzie** [comment]
Also, it starts with a scrollbar and looks normal, and then when you scroll it disappears and you see this.

**Comment by jesshmusic** [comment]
Which browser is that?
I'll check into it this weekend.

**Comment by jesshmusic** [comment]
Can someone check this and see what it looks like now?

**Comment by mzenzie** [comment]
It's fine now
