### ISSUE TITLE
Can put in very high number for number of lessons

### ISSUE THREAD

**Issue by btamaska** [mzenzie/320MusicLessonPlanner#73]
This is not really a bug, but maybe the number of lessons should be capped at some level.

**Comment by jesshmusic** [comment]
This would be a difficult number to estimate, because some teachers may want a lot of lessons scheduled. (Like for students signed on indefinitely).

**Comment by jesshmusic** [comment]
Closing, because some teachers will need to be able to schedule many lessons. I will set an arbitrary max to avoid setting up a very very very large number and filling the database.
