### ISSUE TITLE
Starting date is ugly

### ISSUE THREAD

**Issue by cassiecorey** [mzenzie/320MusicLessonPlanner#79]
looks like: Sat Apr 18 2015 14:00:00 GMT-0400 (EDT)
this is kind of ugly and intimidating to the average user

**Comment by jesshmusic** [comment]
Fixed. Changed the input type from `text` to `date`... oddly, I tried this before and it didn't work... now it does. I give up on JavaScript.

**Comment by jesshmusic** [comment]
So... the old fix broke creating new students... therefore, the ugly dates have returned. :(

**Comment by jesshmusic** [comment]
Fixed again. Backed off AngularJS to version 1.2.16, because 1.3.7 used a different version of input types than the datepicker module.
