### ISSUE TITLE
Broken scaling on 1920x1080 resolution monitors (minor)

### ISSUE THREAD

**Issue by mzenzie** [mzenzie/320MusicLessonPlanner#86]
![image](https://cloud.githubusercontent.com/assets/1862891/7361854/546f9248-ed2e-11e4-942e-31358d7d8386.png)

Text overflows the picture space. This is really minor, and probably not something we need to fix before 1.0.0

**Comment by jesshmusic** [comment]
Fixed by making the background of the Jumbotron black in the styles.css.
