### ISSUE TITLE
Lesson Time not updated when adding new student

### ISSUE THREAD

**Issue by cassiecorey** [mzenzie/320MusicLessonPlanner#9]
LessonTime is a variable stored in a different table which means more steps are needed to access it when updating the list of students after adding a new student.

**Comment by cassiecorey** [comment]
Update: for Alpha Release, Lesson Time was removed as a field for displaying student information. Replaced with Birthday since birthday comes from the same table as other fields so it can be accessed easily. For Beta release, this should be switched back to Lesson Time since it is more critical information than birthday.
![image](https://cloud.githubusercontent.com/assets/8444201/6543698/6af33e64-c4f4-11e4-9ae7-6c4b8c431b0f.png)

**Comment by jesshmusic** [comment]
Fixed as of Beta
